pub use stonepyre_protocol::{
    ActionState,
    ClientMsg,
    HarvestNodeEvent,
    HarvestNodeEventKind,
    HarvestNodeSnapshot,
    HarvestResult,
    InventoryDelta,
    InventoryItemSnapshot,
    InventorySnapshot,
    InteractionAction,
    InteractionTarget,
    PlayerActionSnapshot,
    PlayerSnapshot,
    ServerMsg,
    WorldSnapshot,
};
